name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake . 
    - name: npm
      run: npm i
    - name: inside npm
      run: cd src && npm i
    - name: make
      run: make

